{% set version = "0.2.5" %}


package:
  name: pytest-watcher
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-watcher/pytest-watcher-{{ version }}.tar.gz
  sha256: 0a220d18b778fbae4d876f8d7d2eb86e63d7d8257cd6b05f42c13aa6625c0b6f

build:
  number: 0
  noarch: python
  entry_points:
    - ptw = pytest_watcher:run
    - pytest-watcher = pytest_watcher:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1.0.0
    - pip
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - watchdog >=2.0.0

test:
  imports:
    - pytest_watcher
  commands:
    - pip check
    - ptw --help
    - pytest-watcher --help
  requires:
    - pip

about:
  home: https://github.com/olzhasar/pytest-watcher
  summary: Continiously runs pytest on changes in *.py files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bryanwweber
